import type { GeneratedContent, StudyChapterContent } from "@/lib/types";
import type { PublicChapterRow } from "@/lib/supabase/data";

const anatomyIntroductionData: StudyChapterContent = {
  chapterId: "anatomy-introduction",
  subject: "正常人体解剖学",
  chapter: "绪论",
  version: "人卫版第3版：申国明、黎晖主编",
  summary: "绪论主要掌握人体解剖学定义、标准解剖学姿势、方位术语、轴和面。考试多以选择题、填空题、判断题和名词解释形式出现。",
  framework: [
    "人体解剖学的定义",
    "人体解剖学的分科",
    "学习人体解剖学的基本观点",
    "人体的组成和分部",
    "标准解剖学姿势",
    "方位术语",
    "轴和面",
  ],
  keyPoints: [
    {
      title: "人体解剖学定义",
      content: "人体解剖学是研究正常人体形态结构及其发生发展规律的科学。",
      level: "A",
    },
    {
      title: "标准解剖学姿势",
      content: "身体直立，两眼平视前方，上肢自然下垂，掌心向前，两足并拢，足尖向前。",
      level: "S",
    },
    {
      title: "方位术语",
      content: "常用方位术语包括上、下、前、后、内侧、外侧、内、外、浅、深、近侧、远侧。",
      level: "S",
    },
    {
      title: "轴",
      content: "人体常用三个轴：垂直轴、矢状轴、冠状轴。",
      level: "B",
    },
    {
      title: "面",
      content: "常用切面包括矢状面、冠状面和水平面。",
      level: "A",
    },
  ],
  cards: [
    {
      id: "intro-card-001",
      title: "人体解剖学定义",
      question: "人体解剖学研究什么？",
      answer: "人体解剖学是研究正常人体形态结构及其发生发展规律的科学。",
      level: "A",
      type: "definition",
    },
    {
      id: "intro-card-002",
      title: "标准解剖学姿势",
      question: "标准解剖学姿势包括哪些要点？",
      answer: "身体直立，两眼平视前方，上肢自然下垂，掌心向前，两足并拢，足尖向前。",
      level: "S",
      type: "must_memorize",
    },
    {
      id: "intro-card-003",
      title: "掌心方向",
      question: "标准解剖学姿势中掌心朝向哪里？",
      answer: "掌心向前。",
      level: "S",
      type: "detail",
    },
    {
      id: "intro-card-004",
      title: "内侧和外侧",
      question: "什么是内侧和外侧？",
      answer: "靠近正中矢状面为内侧，远离正中矢状面为外侧。",
      level: "S",
      type: "direction_term",
    },
    {
      id: "intro-card-005",
      title: "近侧和远侧",
      question: "近侧和远侧主要用于描述哪里？",
      answer: "主要用于四肢，靠近肢体根部为近侧，远离肢体根部为远侧。",
      level: "S",
      type: "direction_term",
    },
    {
      id: "intro-card-006",
      title: "矢状面",
      question: "矢状面将人体分为哪两部分？",
      answer: "左、右两部分。",
      level: "A",
      type: "plane",
    },
    {
      id: "intro-card-007",
      title: "冠状面",
      question: "冠状面又称什么？将人体分为哪两部分？",
      answer: "冠状面又称额状面，将人体分为前、后两部分。",
      level: "A",
      type: "plane",
    },
    {
      id: "intro-card-008",
      title: "水平面",
      question: "水平面又称什么？将人体分为哪两部分？",
      answer: "水平面又称横断面，将人体分为上、下两部分。",
      level: "A",
      type: "plane",
    },
  ],
  quickReview: [
    "人体解剖学：研究正常人体形态结构及其发生发展规律的科学。",
    "标准解剖学姿势：身体直立、两眼平视、上肢下垂、掌心向前、两足并拢、足尖向前。",
    "内侧：靠近正中矢状面。",
    "外侧：远离正中矢状面。",
    "浅：靠近体表。",
    "深：远离体表。",
    "近侧：靠近肢体根部。",
    "远侧：远离肢体根部。",
    "矢状面：分左右。",
    "正中矢状面：分左右相等两半。",
    "冠状面/额状面：分前后。",
    "水平面/横断面：分上下。",
    "垂直轴：上下方向。",
    "矢状轴：前后方向。",
    "冠状轴：左右方向。",
  ],
  quiz: [
    {
      id: "intro-q001",
      type: "single_choice",
      question: "人体解剖学主要研究的是：",
      options: ["人体生理功能", "正常人体形态结构及其发生发展规律", "疾病发生机制", "药物作用规律"],
      answer: "正常人体形态结构及其发生发展规律",
      explanation: "人体解剖学是研究正常人体形态结构及其发生发展规律的科学。",
    },
    {
      id: "intro-q002",
      type: "single_choice",
      question: "描述人体结构位置关系时，通常以哪种姿势为标准？",
      options: ["坐位", "仰卧位", "标准解剖学姿势", "俯卧位"],
      answer: "标准解剖学姿势",
      explanation: "解剖学描述以标准解剖学姿势为统一标准。",
    },
    {
      id: "intro-q003",
      type: "single_choice",
      question: "标准解剖学姿势中，掌心应朝向：",
      options: ["前方", "后方", "内侧", "外侧"],
      answer: "前方",
      explanation: "标准解剖学姿势中，上肢自然下垂，掌心向前。",
    },
    {
      id: "intro-q004",
      type: "single_choice",
      question: "靠近正中矢状面的方位称为：",
      options: ["外侧", "内侧", "浅", "深"],
      answer: "内侧",
      explanation: "靠近正中矢状面为内侧。",
    },
    {
      id: "intro-q005",
      type: "single_choice",
      question: "将人体分为前、后两部分的切面是：",
      options: ["矢状面", "冠状面", "水平面", "横断面"],
      answer: "冠状面",
      explanation: "冠状面又称额状面，将人体分为前、后两部分。",
    },
    {
      id: "intro-q006",
      type: "single_choice",
      question: "将人体分为上、下两部分的切面是：",
      options: ["矢状面", "冠状面", "水平面", "额状面"],
      answer: "水平面",
      explanation: "水平面又称横断面，将人体分为上、下两部分。",
    },
    {
      id: "intro-q007",
      type: "fill_blank",
      question: "标准解剖学姿势中，上肢自然下垂，掌心向____。",
      answer: "前",
      explanation: "标准解剖学姿势中掌心向前。",
    },
    {
      id: "intro-q008",
      type: "fill_blank",
      question: "靠近正中矢状面为____，远离正中矢状面为____。",
      answer: "内侧；外侧",
      explanation: "这是方位术语中的内侧和外侧。",
    },
    {
      id: "intro-q009",
      type: "true_false",
      question: "标准解剖学姿势中，掌心向后。",
      answer: "错误",
      explanation: "标准解剖学姿势中掌心向前。",
    },
    {
      id: "intro-q010",
      type: "true_false",
      question: "近侧和远侧主要用于描述四肢。",
      answer: "正确",
      explanation: "近侧和远侧主要用于描述四肢结构。",
    },
    {
      id: "intro-q011",
      type: "short_answer",
      question: "简述标准解剖学姿势。",
      answer: "标准解剖学姿势是描述人体结构位置关系的统一标准。其要点包括：身体直立，两眼平视前方，上肢自然下垂，掌心向前，两足并拢，足尖向前。",
      explanation: "答题时抓住身体直立、两眼平视、掌心向前、两足并拢、足尖向前。",
    },
    {
      id: "intro-q012",
      type: "short_answer",
      question: "简述人体常用的三个切面。",
      answer: "人体常用切面包括矢状面、冠状面和水平面。矢状面将人体分为左、右两部分；正中矢状面将人体分为左右相等两半；冠状面又称额状面，将人体分为前、后两部分；水平面又称横断面，将人体分为上、下两部分。",
      explanation: "重点区分矢状面、冠状面和水平面分别分左右、前后、上下。",
    },
  ],
};

const generatedContent: GeneratedContent = {
  chapterTitle: anatomyIntroductionData.chapter,
  summary: anatomyIntroductionData.summary,
  knowledgeTree: [
    {
      title: "正常人体解剖学 > 绪论",
      children: anatomyIntroductionData.framework,
    },
  ],
  keyPoints: anatomyIntroductionData.keyPoints.map((point) => ({
    title: point.title,
    explanation: point.content,
    examHint: `重要等级：${point.level}`,
  })),
  terms: [],
  flashcards: anatomyIntroductionData.cards.map((card) => ({
    front: card.question,
    back: card.answer,
    tag: `${card.title} / ${card.level} / ${card.type}`,
  })),
  quiz: anatomyIntroductionData.quiz.map((quiz) => ({
    question: quiz.question,
    options: quiz.options ?? [],
    answer: quiz.answer,
    explanation: quiz.explanation,
    relatedPoint: quiz.type,
  })),
  reviewPlan: [],
  studyData: anatomyIntroductionData,
};

export const staticChapters: PublicChapterRow[] = [
  {
    id: anatomyIntroductionData.chapterId,
    owner_id: null,
    owner_email: null,
    course_name: anatomyIntroductionData.subject,
    chapter_title: anatomyIntroductionData.chapter,
    source_text: "用户提供的《正常人体解剖学-绪论》JSON 静态复习资料。",
    generated_content: generatedContent,
    created_at: "2026-06-07T00:00:00.000Z",
    updated_at: "2026-06-07T00:00:00.000Z",
  },
];

export function findStaticChapterById(id: string) {
  return staticChapters.find((chapter) => chapter.id === id) ?? null;
}
